FROM node:18-alpine AS build

WORKDIR /usr/src/app

COPY package.json package-lock.json ./
RUN npm install --force

COPY . .
RUN npm run build -- --configuration production

FROM nginx:stable-alpine AS final
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist/palette-gen-frontend /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]